DROP TABLE IF EXISTS rsvps;

CREATE TABLE rsvps (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  guest_name TEXT NOT NULL,
  contact TEXT NOT NULL,
  adult_count INTEGER NOT NULL DEFAULT 1,
  child_count INTEGER NOT NULL DEFAULT 1,
  child_names TEXT NOT NULL DEFAULT '',
  notes TEXT NOT NULL DEFAULT '',
  attending INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
